-- ===========================================================================
-- 002_accounts.sql
--
-- 帳戶表。balance 是「快照」—— 它可以隨時從 entries 重算出來（見 004）。
-- 這個「快照 vs 事實」的關係就是整個系統的自我檢查機制：
-- 只要 balance 跟重算結果對不上，就代表發生了 lost update。
--
-- 一個帳戶綁定一個幣別，終身不變。「Alice 的美金帳戶」和「Alice 的日圓帳戶」
-- 是兩個不同的 account 列，各有自己的 id 和餘額。
-- ===========================================================================

BEGIN;

CREATE TABLE accounts (
  -- IDENTITY 讓 Postgres 產生 id，但也允許程式明確指定（BY DEFAULT 而非 ALWAYS），
  -- 這樣測試資料可以用固定 id（1001、2002）方便閱讀。
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  owner_id BIGINT  NOT NULL,
  currency CHAR(3) NOT NULL REFERENCES currencies(code),

  -- 餘額，單位是該幣別的最小單位（見 001_currencies.sql）。
  balance BIGINT NOT NULL DEFAULT 0,

  -- 一般使用者帳戶不得為負。系統帳戶（發行、清算、手續費歸集）必須能為負，
  -- 否則錢無法進入系統 —— double-entry 的世界裡「憑空生出一筆錢」
  -- 其實是「從系統帳戶轉出去」，系統帳戶因此會累積負餘額。
  allow_negative BOOLEAN NOT NULL DEFAULT FALSE,

  -- 0 = ACTIVE, 1 = CLOSED。
  -- 關戶只改狀態，永不 DELETE —— 因為 entries 永遠指向它，而且稽核需要歷史。
  status SMALLINT NOT NULL DEFAULT 0,

  -- 每次餘額變動 +1。Stage 6 可以拿來做樂觀鎖的版本檢查，
  -- 現階段主要是給 debug 用：看一個帳戶被動過幾次。
  version BIGINT NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- === 約束 ===============================================================

  -- 防超額扣款的最後一道防線。程式在記憶體裡先檢查過，但如果程式有 bug，
  -- 這條 CHECK 會讓整個交易 ROLLBACK，而不是讓餘額變成負的。
  CONSTRAINT accounts_balance_non_negative
    CHECK (allow_negative OR balance >= 0),

  CONSTRAINT accounts_status_valid
    CHECK (status IN (0, 1)),

  -- 一個人在同一幣別只能有一個帳戶。
  CONSTRAINT accounts_owner_currency_unique
    UNIQUE (owner_id, currency),

  -- 這條看起來很奇怪 —— id 已經是 PRIMARY KEY，為什麼還要 UNIQUE(id, currency)？
  --
  -- 因為 Postgres 的外鍵只能指向「有唯一索引的欄位組合」。
  -- 有了這個唯一索引，003 和 004 就能用「複合外鍵」把幣別一致性
  -- 交給資料庫強制執行 —— 例如一筆 entry 不可能標成跟它的帳戶不同的幣別，
  -- 因為 (account_id, currency) 這個組合在 accounts 裡根本不存在。
  --
  -- 這是把「應用層的檢查」下推成「資料庫的結構性保證」的技巧：
  -- 不是「我們記得要檢查」，而是「錯的資料寫不進去」。
  CONSTRAINT accounts_id_currency_unique
    UNIQUE (id, currency)
);

COMMENT ON TABLE  accounts IS
  '帳戶。一個帳戶綁定一個幣別。balance 是快照，可從 entries 重算驗證。';
COMMENT ON COLUMN accounts.balance IS
  '餘額，單位為該幣別最小單位。必須恆等於 SUM(entries.amount WHERE account_id = id)。';
COMMENT ON COLUMN accounts.allow_negative IS
  'TRUE 僅限系統帳戶（發行/清算）。一般使用者帳戶為 FALSE，由 CHECK 擋住負餘額。';
COMMENT ON CONSTRAINT accounts_id_currency_unique ON accounts IS
  '供 transactions 與 entries 建立複合外鍵，用資料庫強制幣別一致性。';

CREATE INDEX accounts_owner_idx ON accounts (owner_id);

INSERT INTO schema_migrations (version, description)
VALUES ('002', 'accounts 帳戶表');

COMMIT;
