-- ===========================================================================
-- 003_transactions.sql
--
-- 交易標頭。一筆 transaction 描述「誰轉給誰、多少錢」，
-- 實際的記帳動作由 004 的兩筆 entry 表達。
--
-- 這張表最重要的欄位是 idempotency_key —— 它是防止重複扣款的
-- 唯一真正保證（記憶體快取只是效能優化，重啟就沒了）。
-- ===========================================================================

BEGIN;

-- 方案 B（write-through）下，交易成功才 COMMIT、失敗整個 ROLLBACK，
-- 所以實際上表裡只會出現 COMMITTED。
-- 保留另外兩個值是為了 Stage 8 可能改成 group commit（會需要 PENDING），
-- 以及未來若要保留失敗紀錄供稽核（FAILED）。
CREATE TYPE tx_status AS ENUM ('PENDING', 'COMMITTED', 'FAILED');

CREATE TABLE transactions (
  -- 由 Postgres 產生 id，不是由 C++ 的 atomic counter。
  --
  -- 這是對 Stage 0 設計的一個修正：行程內的 atomic counter 在重啟後會歸零、
  -- 多實例部署會互撞。IDENTITY 背後是 Postgres 的 sequence，
  -- 跨重啟、跨連線、跨實例都保證唯一。
  -- 記憶體裡的 atomic counter 保留給 Journal 的內部序號與 metrics 用。
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 900000) PRIMARY KEY,

  -- 由 client 提供。同一筆請求重送多次，只會成功寫入一次。
  -- 第二次會撞 UNIQUE → SQLSTATE 23505 → 應用層改成查詢原交易回傳原結果。
  idempotency_key TEXT NOT NULL,

  status tx_status NOT NULL DEFAULT 'COMMITTED',

  currency CHAR(3) NOT NULL REFERENCES currencies(code),

  -- 轉帳金額，恆為正。方向由 debit/credit 兩個欄位表達，不靠正負號。
  amount BIGINT NOT NULL,

  debit_account_id  BIGINT NOT NULL,   -- 錢從這裡出去
  credit_account_id BIGINT NOT NULL,   -- 錢進到這裡

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- === 約束 ===============================================================

  -- 冪等性的真正保證。這一行是「重送不會扣兩次錢」的全部依據。
  CONSTRAINT transactions_idempotency_key_unique UNIQUE (idempotency_key),

  CONSTRAINT transactions_amount_positive CHECK (amount > 0),

  CONSTRAINT transactions_idempotency_key_not_blank
    CHECK (length(trim(idempotency_key)) > 0),

  -- 擋自己轉給自己。
  -- 這在資料庫層是「資料不合理」，在程式層還有另一個更嚴重的理由：
  -- 若不擋掉，LedgerCore 排序後 lo == hi，會對同一把非遞迴 mutex 鎖兩次
  -- —— 未定義行為，實務上就是自己把自己卡死。
  CONSTRAINT transactions_no_self_transfer
    CHECK (debit_account_id <> credit_account_id),

  -- === 複合外鍵：用資料庫強制「兩腳幣別必須相同」=========================
  --
  -- 這兩條外鍵指向 accounts(id, currency)（002 建立的唯一索引）。
  -- 效果是：transaction 的 currency 欄位必須同時等於
  -- 借方帳戶的幣別「以及」貸方帳戶的幣別。
  --
  -- 換句話說，「拿美金帳戶轉給日圓帳戶」這種資料在結構上就寫不進去，
  -- 不需要應用層記得檢查，也不需要額外的觸發器。
  CONSTRAINT transactions_debit_currency_fk
    FOREIGN KEY (debit_account_id, currency)  REFERENCES accounts (id, currency),
  CONSTRAINT transactions_credit_currency_fk
    FOREIGN KEY (credit_account_id, currency) REFERENCES accounts (id, currency)
);

COMMENT ON TABLE  transactions IS
  '交易標頭。一筆 transaction 對應 entries 表中恰好兩筆相加為零的 entry。';
COMMENT ON COLUMN transactions.idempotency_key IS
  'client 提供的冪等鍵。UNIQUE 約束是防重複扣款的唯一真正保證。';
COMMENT ON COLUMN transactions.amount IS
  '轉帳金額，恆為正。方向由 debit_account_id / credit_account_id 表達。';
COMMENT ON CONSTRAINT transactions_debit_currency_fk ON transactions IS
  '複合外鍵，強制交易幣別 = 借方帳戶幣別。跨幣別轉帳在結構上無法寫入。';

-- 對帳單與稽核查詢：找某帳戶的交易，通常要依時間倒序。
CREATE INDEX transactions_debit_idx  ON transactions (debit_account_id,  id DESC);
CREATE INDEX transactions_credit_idx ON transactions (credit_account_id, id DESC);
CREATE INDEX transactions_created_at_idx ON transactions (created_at DESC);

INSERT INTO schema_migrations (version, description)
VALUES ('003', 'transactions 交易標頭表 + 冪等鍵 + 幣別複合外鍵');

COMMIT;
