-- ===========================================================================
-- 004_entries.sql
--
-- 分錄表 —— 整個系統的「事實」。
--
-- 核心概念：entry 是不可變的事實，balance 是可變的快照。
--   事實永遠不改；快照隨時可以從事實重算。
--   兩者對不上 = 發生了 lost update。這就是併發 bug 的偵測器。
--
-- 一筆轉帳 = 恰好兩筆 entry，金額一負一正，相加為零：
--
--   transaction 900001：Alice(1001) 轉 $50.00 給 Bob(2002)
--     entry A: account 1001, amount = -5000   （借方 DEBIT，錢出去）
--     entry B: account 2002, amount = +5000   （貸方 CREDIT，錢進來）
--                                    -------
--                            相加 =        0   ← 這就是「雙式記帳」
--
-- 為什麼用帶正負號的金額，而不是 direction 列舉 + 恆正金額：
--   因為不變式可以直接用一條 SQL 驗證：
--     SELECT transaction_id FROM entries
--     GROUP BY transaction_id HAVING SUM(amount) <> 0;
--   回傳空集合就代表整個帳本是平的。用 direction 列舉的話這條查詢會變成
--   一堆 CASE WHEN，而且無法直接做 SUM 驗證。
--   代價是不符傳統會計的 DR/CR 呈現 —— 那用一個 generated column 補回來即可。
-- ===========================================================================

BEGIN;

CREATE TABLE entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  transaction_id BIGINT NOT NULL REFERENCES transactions(id),
  account_id     BIGINT NOT NULL,
  currency       CHAR(3) NOT NULL,

  -- 負 = 借方（錢出去），正 = 貸方（錢進來）。永遠不會是 0。
  amount BIGINT NOT NULL,

  -- 寫入這筆 entry 之後，該帳戶的餘額。
  -- 純粹是稽核用的冗餘欄位：有了它，對帳單可以直接顯示每筆交易後的餘額，
  -- 不用逐筆累加；也讓「哪一筆開始對不上」變得一眼可見。
  balance_after BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- === 約束 ===============================================================

  CONSTRAINT entries_amount_nonzero CHECK (amount <> 0),

  -- 固定兩腳的設計下，同一筆交易裡一個帳戶最多出現一次。
  -- 這條同時擋掉了「兩腳都是同一個帳戶」的畸形資料。
  CONSTRAINT entries_one_leg_per_account UNIQUE (transaction_id, account_id),

  -- 複合外鍵：entry 的幣別必須等於它所屬帳戶的幣別。
  -- 跟 003 同樣的技巧 —— 把檢查下推成結構性保證。
  CONSTRAINT entries_account_currency_fk
    FOREIGN KEY (account_id, currency) REFERENCES accounts (id, currency)
);

COMMENT ON TABLE  entries IS
  '分錄。不可變、只增不改。一筆 transaction 對應恰好兩筆相加為零的 entry。';
COMMENT ON COLUMN entries.amount IS
  '負 = 借方（錢出去），正 = 貸方（錢進來）。同一交易的兩筆相加必為 0。';
COMMENT ON COLUMN entries.balance_after IS
  '寫入本筆後該帳戶的餘額。稽核用冗餘欄位，讓對帳單不必逐筆累加。';

-- 方便閱讀的衍生欄位：把帶號金額翻譯回會計慣用的 DR/CR 呈現。
-- STORED 表示實際存在磁碟上，查詢時不用重算。
ALTER TABLE entries
  ADD COLUMN direction TEXT
  GENERATED ALWAYS AS (CASE WHEN amount < 0 THEN 'DEBIT' ELSE 'CREDIT' END) STORED;

COMMENT ON COLUMN entries.direction IS
  '由 amount 正負號自動衍生。正確性用帶號金額保證，這欄只負責呈現。';

-- 對帳單查詢：某帳戶的所有分錄，時間順序。
CREATE INDEX entries_account_idx ON entries (account_id, id);
-- 不變式檢查與「這筆交易的兩腳是誰」查詢。
CREATE INDEX entries_transaction_idx ON entries (transaction_id);


-- ===========================================================================
-- 保證一：每筆交易恰好兩筆 entry，且相加為零
--
-- 為什麼不能用 CHECK：CHECK 只能看「同一列」的欄位。這裡的規則牽涉到
-- 同一個 transaction_id 底下的「多列」，CHECK 表達不了。
--
-- 為什麼必須 DEFERRABLE INITIALLY DEFERRED：
--   兩筆 entry 是分兩次 INSERT 的。如果觸發器在第一次 INSERT 後立刻檢查，
--   那時只有一筆、總和不是零，會直接爆掉 —— 但那是正常的中間狀態。
--   DEFERRED 讓檢查延後到 COMMIT 的那一刻，此時兩筆都在，才是有意義的檢查點。
--
-- 效果：資料庫本身會拒絕提交一筆不平的交易。
--       不是「應用程式記得要平衡」，是「不平的資料 COMMIT 不進去」。
-- ===========================================================================

CREATE FUNCTION assert_transaction_balanced() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  leg_count INTEGER;
  leg_sum   BIGINT;
BEGIN
  SELECT count(*), coalesce(sum(amount), 0)
    INTO leg_count, leg_sum
    FROM entries
   WHERE transaction_id = NEW.transaction_id;

  IF leg_count <> 2 THEN
    RAISE EXCEPTION
      'transaction % 有 % 筆分錄，必須恰好 2 筆（固定兩腳設計）',
      NEW.transaction_id, leg_count
      USING ERRCODE = 'check_violation';
  END IF;

  IF leg_sum <> 0 THEN
    RAISE EXCEPTION
      'transaction % 的分錄總和為 %，必須為 0（雙式記帳不變式 I1）',
      NEW.transaction_id, leg_sum
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;   -- AFTER 觸發器的回傳值會被忽略
END;
$$;

COMMENT ON FUNCTION assert_transaction_balanced() IS
  '在 COMMIT 時驗證不變式 I1：每筆交易恰好兩筆分錄且相加為零。';

CREATE CONSTRAINT TRIGGER entries_must_balance
  AFTER INSERT ON entries
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION assert_transaction_balanced();


-- ===========================================================================
-- 保證二：entries 只增不改（append-only）
--
-- 稽核軌跡的定義就是「寫下去的事實不會被改寫」。要沖銷一筆錯帳，
-- 正確做法是再記一筆方向相反的交易，而不是回頭去改或刪原本那筆。
--
-- 這條觸發器讓「改歷史」在資料庫層直接不可能 —— 包括不小心的 UPDATE、
-- 手滑的 DELETE，以及未來某個人「只是想修一下」的念頭。
-- ===========================================================================

CREATE FUNCTION reject_entry_mutation() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'entries 是 append-only 的稽核軌跡，不允許 %。要沖銷請記一筆反向交易。',
    TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$;

COMMENT ON FUNCTION reject_entry_mutation() IS
  '擋下 entries 的 UPDATE / DELETE，維持稽核軌跡不可竄改。';

CREATE TRIGGER entries_no_update
  BEFORE UPDATE ON entries
  FOR EACH ROW EXECUTE FUNCTION reject_entry_mutation();

CREATE TRIGGER entries_no_delete
  BEFORE DELETE ON entries
  FOR EACH ROW EXECUTE FUNCTION reject_entry_mutation();


INSERT INTO schema_migrations (version, description)
VALUES ('004', 'entries 分錄表 + 平衡約束觸發器 + append-only 保護');

COMMIT;
